spring:
  application:
    name: gateway
  redis:
    port: 6379
    host: localhost

server:
  port: 8080

gateway:
  clients:
    -
      name: limited
      key: c2bac05d-1097-4f53-add3-492b17853350
      permissions: 
        - movies-service
        - music-service-v1
    -
      name: full
      key: 3546c9bd-1a32-4742-90b9-86e112287eca
      permissions:
        - movies-service
        - music-service-v1
        - music-service-v2

  services:
    -
      key: movies-service
      url: http://localhost:8083
      path: /api/movies
      prefix: 2
    -
      key: music-service-v1
      url: http://localhost:8084
      path: /api/music/v1
      prefix: 3
    -
      key: music-service-v2
      url: http://localhost:8084
      path: /api/music/v2
      prefix: 3