spring:
  application:
    name: gateway
  redis:
    port: 6379
    host: localhost
    
  cloud:
    gateway:
      routes:
        - id: movies-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/movies/**
          filters:
            - RewritePath=/api/movies/(?<segment>.*), /$\{segment}
        - id: music-service-v1
          uri: http://localhost:8084
          predicates:
            - Path=/api/music/v1/**
          filters:
            - RewritePath=/api/music/v1/(?<segment>.*), /v1/$\{segment}
        - id: music-service-v2
          uri: http://localhost:8084
          predicates:
            - Path=/api/music/v2/**
          filters:
            - RewritePath=/api/music/v2/(?<segment>.*), /v2/$\{segment}

server:
  port: 8080

gateway:
  clients:
    -
      name: limited
      key: c2bac05d-1097-4f53-add3-492b17853350
      services: 
        - movies-service
        - music-service-v1
    -
      name: full
      key: 3546c9bd-1a32-4742-90b9-86e112287eca
      services:
        - movies-service
        - music-service-v1
        - music-service-v2